"""Asking KWin to blur what is behind the window.

Plasma 6.7 replaced ``org_kde_kwin_blur_manager`` with the standard
``ext-background-effect-v1``. Qt does not speak it and PySide6 exposes no
``wl_surface``, so the request goes through a small C shim whose protocol code
is generated by ``wayland-scanner`` and whose only job is to hand two pointers
to the compositor.

Entirely optional. Without the shim, without the protocol, or on X11 or another
desktop, the window is simply translucent and unblurred, and nothing here
raises. There is no fallback that captures the screen or fakes the effect: the
compositor does it or it does not happen.

The whole interaction is one registry roundtrip and one ``set_blur_region`` at
startup. Nothing is periodic and nothing repeats on resize or repaint.
"""

from __future__ import annotations

import ctypes
from pathlib import Path

LIBRARY_NAME = "libkairoblur.so"

#: Searched in order, package directory first so a source checkout works
#: without installing anything.
SEARCH_PATHS = (
    Path(__file__).parent / "native" / LIBRARY_NAME,
    Path(__file__).parent / LIBRARY_NAME,
)

RESULTS = {
    0: "blur active",
    -1: "no display or surface pointer",
    -2: "the window handle was not a wl_surface",
    -3: "could not read the Wayland registry",
    -4: "this compositor does not offer ext-background-effect-v1",
    -5: "the compositor refused the effect object",
}


def library_path():
    for candidate in SEARCH_PATHS:
        if candidate.is_file():
            return candidate
    return None


class Blur:
    """Loads the shim if it is there, and says plainly when it is not."""

    def __init__(self) -> None:
        self._library = None
        self.status = "not attempted"
        self.active = False

        path = library_path()
        if path is None:
            self.status = ("blur unavailable — optional shim not built "
                           "(kairo/qt/native/build.sh)")
            return
        try:
            library = ctypes.CDLL(str(path))
            library.kairo_blur_available.argtypes = [ctypes.c_void_p]
            library.kairo_blur_available.restype = ctypes.c_int
            library.kairo_blur_enable.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
            library.kairo_blur_enable.restype = ctypes.c_int
        except OSError as exc:
            self.status = f"blur unavailable — shim would not load ({exc})"
            return
        self._library = library

    # -- pointers Qt already owns ------------------------------------------

    @staticmethod
    def _display():
        from PySide6.QtGui import QGuiApplication

        application = QGuiApplication.instance()
        if application is None:
            return None
        native = application.nativeInterface()
        getter = getattr(native, "display", None) if native else None
        try:
            return getter() if callable(getter) else None
        except Exception:
            return None

    @staticmethod
    def _surface(window):
        handle = window.windowHandle()
        if handle is None:
            return None
        try:
            return int(handle.winId())
        except Exception:
            return None

    # -- the request --------------------------------------------------------

    def supported(self) -> bool:
        if self._library is None:
            return False
        display = self._display()
        if not display:
            self.status = "blur unavailable — not a Wayland session"
            return False
        try:
            return bool(self._library.kairo_blur_available(ctypes.c_void_p(display)))
        except Exception as exc:
            self.status = f"blur unavailable — {exc}"
            return False

    def apply(self, window) -> bool:
        """Request blur for ``window``. Never raises; sets ``status``."""
        if self._library is None:
            return False
        if not self.supported():
            if self.status in ("not attempted", ""):
                self.status = ("blur unavailable — this compositor does not "
                               "offer ext-background-effect-v1")
            return False

        display, surface = self._display(), self._surface(window)
        if not display or not surface:
            self.status = "blur unavailable — Qt withheld a surface handle"
            return False
        try:
            result = self._library.kairo_blur_enable(ctypes.c_void_p(display),
                                                     ctypes.c_void_p(surface))
        except Exception as exc:
            self.status = f"blur unavailable — {exc}"
            return False

        self.active = result == 0
        self.status = RESULTS.get(result, f"blur unavailable — code {result}")
        return self.active
