/*
 * A minimal bridge to ext-background-effect-v1.
 *
 * Everything protocol-specific in here is generated by wayland-scanner from
 * the XML that ships with wayland-protocols, so the marshalling is produced by
 * the same tool every native client uses and checked by the compiler. The
 * Python side only ever hands over two pointers it already owns: the
 * wl_display Qt connected with, and the wl_surface of the window.
 *
 * Deliberately does no roundtrips of its own beyond a single one at setup.
 * There is no thread, no loop and nothing periodic: a blur region is set once
 * and the compositor honours it until the surface goes away.
 */
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <wayland-client.h>
#include "ext-background-effect-v1-client-protocol.h"

struct state {
    struct ext_background_effect_manager_v1 *manager;
    uint32_t capabilities;
};

static void handle_global(void *data, struct wl_registry *registry,
                          uint32_t name, const char *interface, uint32_t version)
{
    struct state *s = data;
    if (strcmp(interface, ext_background_effect_manager_v1_interface.name) == 0) {
        s->manager = wl_registry_bind(registry, name,
                                      &ext_background_effect_manager_v1_interface,
                                      version < 1 ? version : 1);
    }
}

static void handle_global_remove(void *data, struct wl_registry *r, uint32_t n) { }

static const struct wl_registry_listener registry_listener = {
    handle_global, handle_global_remove
};

/* Returns 1 when the compositor advertises the protocol, 0 otherwise. */
int kairo_blur_available(void *display_ptr)
{
    struct wl_display *display = display_ptr;
    if (!display) return 0;

    struct state s = { NULL, 0 };
    struct wl_registry *registry = wl_display_get_registry(display);
    if (!registry) return 0;
    wl_registry_add_listener(registry, &registry_listener, &s);
    wl_display_roundtrip(display);

    int found = s.manager != NULL;
    if (s.manager) ext_background_effect_manager_v1_destroy(s.manager);
    wl_registry_destroy(registry);
    return found;
}

/*
 * Blur everything behind the surface. Passing a NULL region means "the whole
 * surface", which is what a translucent window wants: the compositor blurs
 * only where the surface is actually see-through.
 *
 * Returns 0 on success, negative on failure.
 */
int kairo_blur_enable(void *display_ptr, void *surface_ptr)
{
    struct wl_display *display = display_ptr;
    struct wl_surface *surface = surface_ptr;
    if (!display || !surface) return -1;

    /* Guard against a bad pointer from the Python side turning into a crash:
       a real wl_surface reports its class. */
    const char *cls = wl_proxy_get_class((struct wl_proxy *) surface);
    if (!cls || strcmp(cls, "wl_surface") != 0) {
        fprintf(stderr, "kairo_blur: not a wl_surface (got %s)\n", cls ? cls : "null");
        return -2;
    }

    struct state s = { NULL, 0 };
    struct wl_registry *registry = wl_display_get_registry(display);
    if (!registry) return -3;
    wl_registry_add_listener(registry, &registry_listener, &s);
    wl_display_roundtrip(display);
    wl_registry_destroy(registry);

    if (!s.manager) return -4;

    struct ext_background_effect_surface_v1 *effect =
        ext_background_effect_manager_v1_get_background_effect(s.manager, surface);
    if (!effect) return -5;

    ext_background_effect_surface_v1_set_blur_region(effect, NULL);
    wl_surface_commit(surface);
    wl_display_flush(display);
    return 0;
}
